# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
      - "/bench"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      julia-dependencies:
        patterns:
          - "*"
